app:
  name: 'skatbot'
  version: '0.9.0'

tg:
  apitoken: "6352576956:AAH1icJcTeDiTI7ppqTuSrXZ8QdQ_sZAGYU"
  baseURL: "skatbot-production.up.railway.app"
http:
  port: '8000'
logger:
  log_level: 'debug'
  rollbar_env: 'skatbot'
redis:
  unique_tts: 15s
  all_tts: 120s
postgres:
  username: "skatbot"
  password: "skatbot"
  host: "localhost"
  port: "5432"
  name: "skatbot"
  pool_max: 10
