app:
  name: 'skatbot'
  version: '0.4.0'

tg:
  apitoken: "6352576956:AAH1icJcTeDiTI7ppqTuSrXZ8QdQ_sZAGYU"
  baseURL: "skatbot-production-3751.up.railway.app"
http:
  port: '8000'
logger:
  log_level: 'debug'
  rollbar_env: 'skatbot'

postgres:
  username: "postgres"
  password: "ab1C42Ca4dEF4E35-AG22gGc4aB1A4*c"
  host: "roundhouse.proxy.rlwy.net"
  port: "31519"
  name: "railway"
  pool_max: 10

