app:
  name: 'skatbot'
  version: '0.4.0'

tg:
  apitoken: "6352576956:AAH1icJcTeDiTI7ppqTuSrXZ8QdQ_sZAGYU"
  baseURL: "skatbot-production.up.railway.app"
http:
  port: '8000'
logger:
  log_level: 'debug'
  rollbar_env: 'skatbot'

postgres:
  username: "postgres"
  password: "Ae6BcFaBc6eCgB6A5be1EaADbDbGgada"
  host: "roundhouse.proxy.rlwy.net"
  port: "53113"
  name: "railway"
  pool_max: 10

